### ISSUE TITLE
possible for p5 to smooth strokes?

### ISSUE THREAD

**Issue by dmalan** [cs50/draw50#8]
![img_0002](https://user-images.githubusercontent.com/788678/44632328-ae303580-a946-11e8-82f4-ff93f7f4a060.PNG)

**Comment by dcoffey3296** [comment]
@dmalan, in the Dan branch in the latest commit, I implemented with vertices rather than drawing lines. It uses Catmull-Rom splines. 
 This is as much smoothing as I think p5 will give us. See what you think. (there are other issues with this implementation)
https://github.com/cs50/draw50/commit/966f387637c15ec4ecd6ed8edf349a6400cf8860

**Comment by dmalan** [comment]
Hm, seems better! Definitely no "smoothing" option for dithering or what not? Still a tad jaggy. 

<img width="389" alt="screen shot 2018-08-27 at 12 54 48 am" src="https://user-images.githubusercontent.com/788678/44641233-017ca500-a994-11e8-8b23-65df834d7edd.png">

**Comment by dcoffey3296** [comment]
Nope, from the documentation this is it this does break all ktnsr features currently, this is the only finger that works. Undo should be easy but erase becomes more complicated

**Comment by dcoffey3296** [comment]
No but paper.js does nicely.  This is resolved.
